image:
  pullPolicy: IfNotPresent
  repository: docker.io
  image: redislabs/redisinsight
  tag: 2.62.0

volumes:
  host:
    /data:
      name: data
      path: "${__cache_dir}/minikube/redisinsight"
      type: DirectoryOrCreate

deployment:
  replicaCount: 1
  updateStrategy:
    type: Recreate

  containerSecurityContext:
    runAsUser: 0

  resources: {}

  env:
    RI_LOG_LEVEL: "warn"

  port: 5540

  livenessProbe:
    endpoint: "/api/health/"

  readinessProbe:
    endpoint: "/api/health/"

ingress:
  className: nginx
  tls:
    - secretName: origin-cert

services:
  redisinsight:
    autoscaling:
      enabled: false

    service:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "redis.${OPERATIONS_DOMAIN}"
