#
#=========================================================================================
# Initialization
#
export OPERATIONS_DOMAIN="${OPERATIONS_SUBDOMAIN}.${PRIMARY_DOMAIN}"
export AUTH_DOMAIN="${AUTH_SUBDOMAIN}.${PRIMARY_DOMAIN}"
export ARGOCD_DOMAIN="argocd.${OPERATIONS_DOMAIN}"
export ZIMAGI_DOMAIN="${ZIMAGI_SUBDOMAIN}.${PRIMARY_DOMAIN}"

export ZIMAGI_APP_NAME="$APP_NAME"

export ZIMAGI_COMMAND_HOST="cmd.${ZIMAGI_DOMAIN}"
export ZIMAGI_COMMAND_PORT=443
export ZIMAGI_DATA_HOST="data.${ZIMAGI_DOMAIN}"
export ZIMAGI_DATA_PORT=443
export ZIMAGI_API_USER="$ZIMAGI_ADMIN_USER"
export ZIMAGI_API_USER_TOKEN="$ZIMAGI_DEFAULT_ADMIN_TOKEN"
export ZIMAGI_API_USER_KEY="$ZIMAGI_ADMIN_API_KEY"

export ZIMAGI_DEFAULT_MODULES='[]'
