image:
  pullPolicy: IfNotPresent
  repository: docker.io
  image: dbeaver/cloudbeaver
  tag: 24.2.5

volumes:
  host:
    /opt/cloudbeaver/workspace:
      name: workspace
      path: "${__cache_dir}/minikube/cloudbeaver"
      type: DirectoryOrCreate

deployment:
  replicaCount: 1
  updateStrategy:
    type: Recreate

  resources: {}

  port: 8978

ingress:
  className: nginx
  tls:
    - secretName: origin-cert

services:
  cloudbeaver:
    autoscaling:
      enabled: false

    service:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "db.${OPERATIONS_DOMAIN}"
