global:
  data:
    ZIMAGI_GITHUB_ORG: "${ZIMAGI_GITHUB_ORG}"

    ZIMAGI_DB_MAX_CONNECTIONS: "${ZIMAGI_DB_MAX_CONNECTIONS}"
    ZIMAGI_REDIS_TYPE: redis

    ZIMAGI_DEBUG: true
    ZIMAGI_DEBUG_COMMAND_PROFILES: true

    ZIMAGI_PARALLEL: "${ZIMAGI_PARALLEL}"
    ZIMAGI_THREAD_COUNT: "${ZIMAGI_THREAD_COUNT}"
    ZIMAGI_MUTEX_TTL_SECONDS: "${ZIMAGI_MUTEX_TTL_SECONDS}"
    ZIMAGI_ENCRYPT_DATA: true

    ZIMAGI_LOG_LEVEL: "${ZIMAGI_LOG_LEVEL}"
    ZIMAGI_RESTART_SERVICES: "${ZIMAGI_RESTART_SERVICES}"
    ZIMAGI_QUEUE_COMMANDS: "${ZIMAGI_QUEUE_COMMANDS}"

    ZIMAGI_AUTO_UPDATE: "${ZIMAGI_AUTO_UPDATE}"
    ZIMAGI_DISABLE_MODULE_INIT: false
    ZIMAGI_DISABLE_MODULE_SYNC: true

    ZIMAGI_EMAIL_HOST: "${ZIMAGI_EMAIL_HOST}"
    ZIMAGI_EMAIL_PORT: "${ZIMAGI_EMAIL_PORT}"
    ZIMAGI_EMAIL_USE_TLS: "${ZIMAGI_EMAIL_USE_TLS}"
    ZIMAGI_EMAIL_SUBJECT_PREFIX: "<${ZIMAGI_APP_NAME}> "

    ZIMAGI_LIB_PVC: ""
    ZIMAGI_HOST_APP_DIR: "${__zimagi_app_dir}"
    ZIMAGI_HOST_LIB_DIR: "${__zimagi_lib_dir}"

    ZIMAGI_DEFAULT_MODULES: "${ZIMAGI_DEFAULT_MODULES}"

command-api:
  data:
    ZIMAGI_SERVER_TIMEOUT: "${ZIMAGI_SERVER_TIMEOUT}"
    ZIMAGI_SERVER_WORKERS: "${ZIMAGI_SERVER_WORKERS}"
    ZIMAGI_DISABLE_HTTPS: "${ZIMAGI_DISABLE_HTTPS}"
    ZIMAGI_ENCRYPT_COMMAND_API: "${ZIMAGI_ENCRYPT_COMMAND_API}"

    ZIMAGI_DISABLE_MODULE_INIT: true
    ZIMAGI_DISABLE_MODULE_SYNC: true
    ZIMAGI_AUTO_UPDATE: true

data-api:
  data:
    ZIMAGI_SERVER_WORKERS: "${ZIMAGI_SERVER_WORKERS}"
    ZIMAGI_DISABLE_HTTPS: "${ZIMAGI_DISABLE_HTTPS}"
    ZIMAGI_ENCRYPT_DATA_API: "${ZIMAGI_ENCRYPT_DATA_API}"
    ZIMAGI_DISABLE_PAGE_CACHE: "${ZIMAGI_DISABLE_PAGE_CACHE}"
    ZIMAGI_PAGE_CACHE_SECONDS: "${ZIMAGI_PAGE_CACHE_SECONDS}"
    ZIMAGI_REST_PAGE_COUNT: "${ZIMAGI_REST_PAGE_COUNT}"

    ZIMAGI_DISABLE_MODULE_INIT: true
    ZIMAGI_DISABLE_MODULE_SYNC: true

scheduler:
  data:
    ZIMAGI_DISABLE_MODULE_INIT: false
    ZIMAGI_DISABLE_MODULE_SYNC: false

controller:
  data:
    ZIMAGI_DISABLE_MODULE_INIT: true
    ZIMAGI_DISABLE_MODULE_SYNC: true

worker:
  data:
    ZIMAGI_WORKER_MAX_PROCESSES: "${ZIMAGI_WORKER_MAX_PROCESSES}"
    ZIMAGI_WORKER_TIMEOUT: "${ZIMAGI_WORKER_TIMEOUT}"
    ZIMAGI_WORKER_CHECK_INTERVAL: "${ZIMAGI_WORKER_CHECK_INTERVAL}"

    ZIMAGI_DISABLE_MODULE_INIT: true
    ZIMAGI_DISABLE_MODULE_SYNC: true
    ZIMAGI_AUTO_UPDATE: false

flower:
  data:
    FLOWER_UNAUTHENTICATED_API: true
